config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#welcome'
  get 'portfolio' => 'pages#portfolio'
  get 'blog' => 'pages#blog'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def welcome 
    end
    def portfolio
    end
    def contact
    end
    def blog 
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # Returns the full title on a per-page basis
    def full_title(page_title = '')
        base_title = "Portfolio"
        if page_title.empty?
            base_title
        else
            "#{page_title} | #{base_title}"
        end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  
    <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
      <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav font-weight-bold">
            <li class="nav-item">
              <%= link_to "Welcome", root_path, class: "nav-link active"%>
            </li>
            <li class="nav-item dropdown">
              
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Portfolio
              </a> 
              <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="navbarDropdownMenuLink">
                <li class="dropdown-item"><a class="nav-link" href="#">HTML/CSS</a></li>
                <li class="dropdown-item"><a class="nav-link" href="#">JavaScript</a></li>
                <li class="dropdown-item dropright">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ruby on Rails</a>
                    <div class="dropdown-menu" role="menu" aria-labelledby="navbarDropdownMenuLink">
                      <a  class="dropdown-item active nav-link" href="#">Example 1</a>
                      <a  class="dropdown-item nav-link" href="#">Example 2</a>
                      <a  class="dropdown-item nav-link" href="#">Example 3</a>
                      <a class="dropdown-item nav-link" href="#">Example 4</a>
                    </div>
                </li>
                <li class="dropdown-item"><a class="nav-link" href="#">PHP</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <%= link_to "Blog", blog_path,  class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_path, class: "nav-link"  %>
            </li> 
          </ul>
        </div>
        <h1 class="navbar-brand name">Clode Uwamariya </h1>
      </div>
    </nav>
</header>
    <%= yield %>
<footer class="footer">
      <div class="media text-right">
        <%= link_to "Contact", contact_path, class: "nav-link" %></a>
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
      </div>
      <small class="copy">
        <a href="#" class="d-block">&copy; 2020 Clode Uwa</a>
      </small>
    
</footer>

<!-- Javascript and jQuery -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="javascripts/unslider-min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/30a4250f2f.js" crossorigin="anonymous"></script>

<script> 
$(function() {
      $('.banner').unslider();
  });
  
</script>
  
  </body>
</html>

app/views/pages/about.html.erb
<%= provide(:title, "About Me") %>
<main class="container about">
    <div class="row mt-5">
        <div class="col-md-6">
            <%=image_tag("pages/KR.jpg", class: "me", alt: "Me") %>
        </div>
        <div class="col-md-6">
            <h2 class="ml-5">Curiosity, Creativity, Attention to Details</h2>
            <br/>
            <h4>Hello. My name is <span class="align-top">Clode Uwa</span></h4>
            <p>Who Am I?.................blah blah blah</p>
        </div>
    </div>
</main>

app/views/pages/blog.html.erb
<%= provide(:title, "Blog")%>
<main class="container">
    <h1>Dive in and feed your curiosity</h1>
    <div class="alert alert-light">
        <p>Have a quick look some interesting ideas on 
        <%=link_to "Medium.com", "https://medium.com/", target: "_blank"%>
    </div>

</main>

app/views/pages/contact.html.erb
<%= provide(:title, "Contact Me") %>

<main>
    <div class="container">
        <h1>Contact Me</h1>
            <a href="#"><i class="fab fa-github"></i></a>
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
    </div>
</main>

app/views/pages/portfolio.html.erb
<%= provide(:title, "Portfolio") %>

<main>
    <div class="banner">
        <%= image_tag("pages/hori.jpg", class: "img") %>
    </div>
</main>
<section>
<div class="container">
    <div class="row">
        <div class="col-md-12">
        <div class= "card border-light">
            <%# <%= image_tag("pages/sample.jpg", class: "card-img-top img", alt: "List of books and prices")%> 
            <div class="card-body">
                <h3>Sample App</h3>
                <%# <p>Lorem ipsum dolor sit amet. Qui totam excepturi et quisquam Quis non consequuntur 
                provident et minus perspiciatis! </p> %>
                <%= link_to "Visit the site", "https://infinite-badlands-4746.herokuapp.com/", target: "_blank"%>
            </div>
        </div>
        </div>
        <div class="col-md-12">
        <div class= "card border-light">
            <%# <%= image_tag("pages/Books2.jpg", class: "card-img-top img", alt: "List of books and prices")%> 
            <div class="card-body">
        <h3>eBook Shop</h3>
        
        <%= link_to "Visit the site", "https://glacial-river-5618.herokuapp.com/", target: "_blank"%>
        </div>
        </div>
        </div>
        <div class="col-md-12">
        <div class= "card border-light">
            <%# <%= image_tag("pages/social.jpg", class: "card-img-top img", alt: "Signup page")%>
            <div class="card-body">
        <h3>Mini Social Portal</h3>
        
        <%= link_to "Visit the site", "https://whispering-tundra-3678.herokuapp.com/", target: "_blank" %>
            </div>
        </div>
        </div>
    </div>
</div>
</section>

app/views/pages/welcome.html.erb
<%= provide(:title, "Welcome") %>
<main>
  <div class="jumbotron jumbotron-fluid bg-light">
    <div class="container text-center jumbo-text">
      <h1 class="display-4">Welcome to my World!</h1>
      <p class="lead line">My name is Clode, I am a full-stack developer. Checkout my projects </p>
      <p class="lead">
        <%= link_to "HTML/CSS", portfolio_path, class: "btn btn-lg view-work font-weight-lighter", role: "button" %> 
        <a class="btn btn-lg view-work font-weight-lighter" href="#" role="button">JavaScript</a>
        <a class="btn btn-lg view-work font-weight-lighter" href="#" role="button">Ruby on Rails</a>
        <a class="btn btn-lg view-work font-weight-lighter" href="#" role="button">PHP</a>
      </p>
    </div>
  </div>
</main> 